### ISSUE TITLE
Entropy not increasing even when jitterentropy runs

### ISSUE THREAD

**Issue by mdsalman729** [smuellerDD/jitterentropy-rngd#1]
Looks like the message is displayed but the entropy does not increase as I could not see any increase in the entropy at all.

Dec 06 03:19:09 root jitterentropy-rngd[30392]: Debug: Injected 256 bytes with an entropy count of 32 bytes of entropy
Dec 06 03:19:09 root jitterentropy-rngd[30392]: Verbose: 256 bytes written to /dev/random
Dec 06 03:19:09 root jitterentropy-rngd[30392]: Debug: Polling /dev/random
Dec 06 03:19:14 root jitterentropy-rngd[30392]: Verbose: Insufficient entropy 138 available
Dec 06 03:19:14 root jitterentropy-rngd[30392]: Debug: Injected 256 bytes with an entropy count of 32 bytes of entropy
Dec 06 03:19:14 root jitterentropy-rngd[30392]: Verbose: 256 bytes written to /dev/random
Dec 06 03:19:14 root jitterentropy-rngd[30392]: Debug: Polling /dev/random
Dec 06 03:19:19 root jitterentropy-rngd[30392]: Verbose: Insufficient entropy 152 available
Dec 06 03:19:19 root jitterentropy-rngd[30392]: Debug: Injected 256 bytes with an entropy count of 32 bytes of entropy
Dec 06 03:19:19 root jitterentropy-rngd[30392]: Verbose: 256 bytes written to /dev/random

**Comment by smuellerDD** [comment]
Am Mittwoch, 6. Dezember 2017, 04:22:16 CET schrieb Mohammed Salman:

Hi Mohammed,

> Looks like the message is displayed but the entropy does not increase as I
> could not see any increase in the entropy at all.

Again, something seems to pull significant data from /dev/random. Use lsof to 
find the culprit.


Ciao
Stephan

**Comment by mdsalman729** [comment]
sh-4.2# lsof /dev/random
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
jitterent 745 root    3w   CHR    1,8      0t0 1032 /dev/random
sh-4.2# cat /proc/sys/kernel/random/entropy_avail
191
sh-4.2# cat /proc/sys/kernel/random/entropy_avail
131
sh-4.2# 

I shut down all other services and only jitterentropy seems to be running, but the entropy is still less consistently less than 200.

With 1.0.4 running on CentOS 6, I see that the value is around 1200-1300 with the same set of services.


Thanks for looking into this. 
Salman

**Comment by smuellerDD** [comment]
Am Mittwoch, 6. Dezember 2017, 09:21:05 CET schrieb Mohammed Salman:

Hi Mohammed,

> sh-4.2# lsof /dev/random
> COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> jitterent 745 root    3w   CHR    1,8      0t0 1032 /dev/random
> sh-4.2# cat /proc/sys/kernel/random/entropy_avail
> 191
> sh-4.2# cat /proc/sys/kernel/random/entropy_avail
> 131
> sh-4.2#
> 
> I shut down all other services and only jitterentropy seems to be running,
> but the entropy is still less consistently less than 200.
> 
> With 1.0.4 running on CentOS 6, I see that the value is around 1200-1300
> with the same set of services.

The difference between 1.0.6 and 1.0.4 is the amount of data sent to the 
kernel in one go. It used to be 256 bytes and I lowered it to 32 bytes.

Do you have constantly forking processes? On older kernels, forking of a 
process depletes the entropy pool by 16 bytes for each fork.



Ciao
Stephan

**Comment by kparamas** [comment]
Hi Stephan,

In followup to mdsalman, if haveged is installed in CentOS7 then entropy_avail is seen above 1500. haveged reference - https://centos.pkgs.org/7/epel-x86_64/haveged-1.9.1-1.el7.x86_64.rpm.html
But only with jitterentropy-rngd-1.0.6 this is not happening. Tried increasing the OVERSAMPLINGFACTOR to 8. That didn't help.

Is there any way the entropy_avail can be increased?

-Kumar

**Comment by smuellerDD** [comment]
Am Montag, 11. Dezember 2017, 19:08:19 CET schrieb kparamas:

Hi kparamas,

> Hi Stephan,
> 
> In followup to mdsalman, if haveged is installed in CentOS7 then
> entropy_avail is seen above 1500. But only with jitterentropy-rngd-1.0.6
> this is not happening. Tried increasing the OVERSAMPLINGFACTOR to 8. That
> didn't help.

This value defines many bits the jitterentropy-rngd has to generate for 
generating 64 bits of entropy. The higher the value, the more work the rngd 
has to do. I.e. a higher value causes more load on your system.

I guess a value of 2 is a good one.

I do not have a Centos7 readily available, but I have an Oracle Linux 7.3 
which is a derivative of RHEL7.3 (just like Centos).

There, after boot, entropy_avail contained 68. When starting the rngd, I get

[sm@ol73 jitterentropy-rngd-1.0.6]$ sudo ./jitterentropy-rngd -v -v -v -v
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install termination signal handler
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 134 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 194 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 251 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 305 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 484 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 528 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 697 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 858 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 1010 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 
bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 1156 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/
random/entropy_avail

You see, the value in the line "... entropy ... available" is the same as you 
find entropy_avail. It increases in 5 second increments.

I.e. it works as expected.

By the way, the kernel is 3.10.0-514.el7.x86_64.

If in your case, the logs are generated by a large amount, you have an entropy 
leech in your system that constantly pulls /dev/random.

Even your haveged example shows that something is wrong in your system. If it 
cannot get beyond 1500, something is not right. It must go above 4000. The 
only difference between my jitterentropy-rngd and the haveged is that I inject 
less data into the kernel per round. I feel that this is more appropriate as 
it does not monopolize the entropy sources.


Ciao
Stephan

**Comment by kparamas** [comment]
Haveged is providing good entropy between 1000 and 2500. It doesn't go beyond 4000.
This is with the same set of services. Even if there is entropy leech haveged is able to provide entropy.

But if we remove the package -- entropy drops less than 200.

We are using the kernel -- 3.10.0-514.26.2.el7.x86_64
