### ISSUE TITLE
NIST 90B testing with Jitter Entropy

### ISSUE THREAD

**Issue by jlramage** [smuellerDD/jitterentropy-rngd#12]
Hello - I'm using the SP800-90B test tarball with intention of running the tests and capturing samples to perform NIST 90B testing here in our lab. From my experience, typical NIST 90B tool testing  takes 8-bit or 1-bit wide samples in binary format. The raw entropy file I've created using the Jitter entropy  testing package produces an ascii file with data samples in one column and "minimum" values in another. 
For example:
8190 4608
6550 4408
4492 4352
My questions are:
- is this the expected output for raw?
- how can I use this output with the NIST 90B tool - do you suggest ascii-binary converters, other
- I assume the first column is the numerical version of 64-bit timing deltas so should I just take the LS 8-bits for the data to feed into the NIST tool?
Anyways, your assistance would be greatly appreciated. In addition, we are testing on a Intel(R) Xeon(R) Gold 6126 processor and could provide some samples and results if I know how to process the CPU Jitter Entropy data successfully.
Regards, James Ramage.

**Comment by smuellerDD** [comment]
Am Dienstag, 28. April 2020, 20:12:39 CEST schrieb jlramage:

Hi jlramage,

> Hello - I'm using the SP800-90B test tarball with intention of running the
> tests and capturing samples to perform NIST 90B testing here in our lab.
> From my experience, typical NIST 90B tool testing  takes 8-bit or 1-bit
> wide samples in binary format. The raw entropy file I've created using the
> Jitter entropy  testing package produces an ascii file with data samples in
> one column and "minimum" values in another. For example:
> 8190 4608
> 6550 4408
> 4492 4352
> My questions are:
> - is this the expected output for raw?

Yes, that is THE true raw unprocessed, unconditioned output

> - how can I use this output with the NIST 90B tool

Depending whether you want to analyze the regular case or the minimum case, 
take all values of column one or two, take the 8 LSB and concatenate those to 
form a bit stream.

Then, this bit stream can be readily processed with the NIST SP800-90B tool.

> - do you suggest
> ascii-binary converters, other

I think you have to write your converter, but it should be quite straight 
forward:

val = strtoul(column);
val &= 0xff;
fwrite(outfd, val, 1);

> - I assume the first column is the numerical
> version of 64-bit timing deltas so should I just take the LS 8-bits for the
> data to feed into the NIST tool?

Precisely - as stated above.

> Anyways, your assistance would be greatly
> appreciated. In addition, we are testing on a Intel(R) Xeon(R) Gold 6126
> processor and could provide some samples and results if I know how to
> process the CPU Jitter Entropy data successfully. Regards, James Ramage.

Thanks a lot, but I have that exact system in front of me  :-)

Ciao
Stephan

**Comment by jlramage** [comment]
Thanks much for the update Stephan! I will close this issue.
