### ISSUE TITLE
Replace rngd with jitterentropy-rngd

### ISSUE THREAD

**Issue by pwFoo** [smuellerDD/jitterentropy-rngd#15]
Hi,

I build a jitterentropy-rngd to replace my rngd running inside of a docker container. I try to build a linuxkit based os with enough entropy to early start a daemon like docker(d) which blocks until there is enough entropy. 

Two questions...

1. Is jitterentropy-rngd faster than rngd to build enough entropy?
2. Do I need to add devices /dev/random and /dev/urandom to the container to benefit from jitterentropy-rngd?

Output with and without devices added are the same... So looks like no need to map the /dev/[u]random to the container?
```
# docker run --rm -ti --cap-add=SYS_ADMIN --cap-drop=ALL --name=rngd --network=none jrngd:latest jitterentropy-rngd -vvvvvvvvvvvvvv
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install termination signal handler
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 2850 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 2851 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 2852 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
^Cjitterentropy-rngd - Debug: Shutting down cleanly
```

**Comment by pwFoo** [comment]
Maybe I'm wrong with "replace"... Do it replace rngd or improve the entropy...?

**Comment by smuellerDD** [comment]
Am Samstag, dem 19.12.2020 um 07:35 -0800 schrieb pwFoo:
> Hi,
> 
> I build a jitterentropy-rngd to replace my rngd running inside of a docker
> container. I try to build a linuxkit based os with enough entropy to early
> start a daemon like docker(d) which blocks until there is enough entropy. 
> 
> Two questions...
> 
> 1. Is jitterentropy-rngd faster than rngd to build enough entropy?

On my system it delivers 35kBit/s. Rngd may pull from RDRAND which is much
much faster. But it may also use slower sources. Thus, it depends...

> 2. Do I need to add devices /dev/random and /dev/urandom to the container to
> benefit from jitterentropy-rngd?

Yes, its sole purpose is to inject data into the Linux kernel. If that is not
desired, the jitterentropy-library can be used together with the crypto
application that is in need of seed data.
> 
> Output with and without devices added are the same... So looks like no need
> to map the /dev/[u]random to the container?

If neither device file is present, the jitterentropy-rngd cannot inject data
into the Linux kernel.

> ```
> # docker run --rm -ti --cap-add=SYS_ADMIN --cap-drop=ALL --name=rngd --
> network=none jrngd:latest jitterentropy-rngd -vvvvvvvvvvvvvv
> jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32
> bytes of entropy
> jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
> jitterentropy-rngd - Debug: Install termination signal handler
> jitterentropy-rngd - Debug: Install alarm signal handler
> jitterentropy-rngd - Debug: Polling /dev/random
> jitterentropy-rngd - Verbose: Wakeup call for alarm on
> /proc/sys/kernel/random/entropy_avail
> jitterentropy-rngd - Debug: Sufficient entropy 2850 available
> jitterentropy-rngd - Debug: Install alarm signal handler
> jitterentropy-rngd - Debug: Polling /dev/random
> jitterentropy-rngd - Verbose: Wakeup call for alarm on
> /proc/sys/kernel/random/entropy_avail
> jitterentropy-rngd - Debug: Sufficient entropy 2851 available
> jitterentropy-rngd - Debug: Install alarm signal handler
> jitterentropy-rngd - Debug: Polling /dev/random
> jitterentropy-rngd - Verbose: Wakeup call for alarm on
> /proc/sys/kernel/random/entropy_avail
> jitterentropy-rngd - Debug: Sufficient entropy 2852 available
> jitterentropy-rngd - Debug: Install alarm signal handler
> jitterentropy-rngd - Debug: Polling /dev/random
> ^Cjitterentropy-rngd - Debug: Shutting down cleanly
> ```
>

**Comment by pwFoo** [comment]
So should I combine rngd with jitterentropy-rngd to have a good entropy?
Before I just used rngd to improve entropy and it looks to works / speed up the needed entropy...

Maybe I just start both, my rngd and the jitterentropy-rngd to speed up on boot time or should rngd just enough?
I don't know much about rng(d) and just use it that way...
```
CMD     ["/usr/sbin/rngd", "-f", "-r", "/dev/urandom", "-p", "/var/run/rngd.pid"]
```

**Comment by smuellerDD** [comment]
Am Samstag, dem 19.12.2020 um 08:33 -0800 schrieb pwFoo:
> So should I combine rngd with jitterentropy-rngd to have a good entropy?

Technically you can combine both. If the rngd has access to another entropy
source you consider appropriate (RDRAND, TPM) it would make sense.

Just FYI: current versions of the rngd have the Jitter-RNG library built in
and thus utilize the Jitter RNG as well. Thus, if you use a current rngd, you
may not need a separate jitterentropy-rngd.

> Before I just used rngd to improve entropy and it looks to works / speed up
> the needed entropy...
> 
> Maybe I just start both, my rngd and the jitterentropy-rngd to speed up on
> boot time or should rngd just enough?
> I don't know much about rng(d) and just use it that way...
> ```
> CMD     ["/usr/sbin/rngd", "-f", "-r", "/dev/urandom", "-p",
> "/var/run/rngd.pid"]
> ```
> 
>

**Comment by pwFoo** [comment]
I built from rngd version 5 here: https://sourceforge.net/projects/gkernel/files/rng-tools/5/
But found 6.10 here: https://github.com/nhorman/rng-tools

So I try to move to rngd 6.10 for testing... Thanks!

By the way... Nice projects I found here! Thanks for sharing software and information about it!

**Comment by pwFoo** [comment]
I'll test with new rngd first, and maybe compare to jitterentropy-rngd.

Question answered, I'll close that issue 👍

**Comment by pwFoo** [comment]
I tried to compile https://github.com/nhorman/rng-tools, but it fails for me... Because jitterentropy-rngd is easy to comile and use and am not sure to really understand the usage of it...

Is jitterentropy-rngd a full rngd which help to get entropy done fast at boot time? Do I need rngd if I use jitterentropy-rngd?
And would there disadvantages to move from rngd to jitterentropy-rngd (only)?

I try to understand which way would be better. rngd v5 was easy to compile, but I have problems to compile rngd v6.10 and more dependencies with the alpine pre-compiled version.
```
/ # ldd $(which rngd)
        /lib/ld-musl-x86_64.so.1 (0x7f93ae6c3000)
        libsysfs.so.2 => /usr/lib/libsysfs.so.2 (0x7f93ae694000)
        librtlsdr.so.0 => /usr/lib/librtlsdr.so.0 (0x7f93ae686000)
        libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7f93ae407000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f93ae6c3000)
        libusb-1.0.so.0 => /usr/lib/libusb-1.0.so.0 (0x7f93ae3ed000)
```

**Comment by smuellerDD** [comment]
Am Samstag, 19. Dezember 2020, 21:54:30 CET schrieb pwFoo:

Hi pwFoo,

> I tried to compile https://github.com/nhorman/rng-tools, but it fails for
> me... Because jitterentropy-rngd is easy to comile and use and am not sure
> to really understand the usage of it...
> 
> Is jitterentropy-rngd a full rngd which help to get entropy done fast at
> boot time?

That is its purpose and goal.

> Do I need rngd if I use jitterentropy-rngd?

No.

> And would there
> disadvantages to move from rngd to jitterentropy-rngd (only)?

You may not use other noise sources rngd has support for like RDRAND or TPM.
> 
> I try to understand which way would be better. rngd v5 was easy to compile,
> but I have problems to compile rngd v6.10 and more dependencies with the
> alpine pre-compiled version. ```
> / # ldd $(which rngd)
>         /lib/ld-musl-x86_64.so.1 (0x7f93ae6c3000)
>         libsysfs.so.2 => /usr/lib/libsysfs.so.2 (0x7f93ae694000)
>         librtlsdr.so.0 => /usr/lib/librtlsdr.so.0 (0x7f93ae686000)
>         libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7f93ae407000)
>         libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f93ae6c3000)
>         libusb-1.0.so.0 => /usr/lib/libusb-1.0.so.0 (0x7f93ae3ed000)
> ```


Ciao
Stephan

**Comment by pwFoo** [comment]
Thanks!
