### ISSUE TITLE
Static build 

### ISSUE THREAD

**Issue by pwFoo** [smuellerDD/jitterentropy-rngd#16]
Is it possible to build a full static binary to run without a "full rootfs" inside of a docker container?
I try to change the `from alpine` to `from scratch`

Looks like there is just one depenency I just added to my scratch image and it seems to work.
```
FROM    scratch

COPY    --from=build /out/jitterentropy-rngd /usr/bin/
COPY    --from=build /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1

CMD     [ "jitterentropy-rngd", "-v" ]
```

**Comment by smuellerDD** [comment]
Am Samstag, dem 19.12.2020 um 07:48 -0800 schrieb pwFoo:
> Is it possible to build a full static binary to run without a "full rootfs"
> inside of a docker container?

I do not know what your container looks like.

But surely you can compile the rngd statically. Simply add -static to the
LDFLAGS.

> I try to change the `from alpine` to `from scratch`
> 
> Looks like there is just one depenency I just added to my scratch image and
> it seems to work.
> ```
> FROM    scratch
> 
> COPY    --from=build /out/jitterentropy-rngd /usr/bin/
> COPY    --from=build /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1
> 
> CMD     [ "jitterentropy-rngd", "-v" ]
> ```
>

**Comment by pwFoo** [comment]
Thanks, I'll try it with `-static`

**Comment by pwFoo** [comment]
Tried it with `.configure` (not exists) and added to make:
```
make LDFLAGS="-static"
```
```
make LDFLAGS="--static"
```

Compiled (example with --static, but both identical...)
```
cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-field-initializers -Wshadow -Wswitch-enum -O2 -fstack-protector-strong    -c -o jitterentropy-base.o jitterentropy-base.c
cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-field-initializers -Wshadow -Wswitch-enum -O2 -fstack-protector-strong    -c -o jitterentropy-rngd.o jitterentropy-rngd.c
cc jitterentropy-base.o jitterentropy-rngd.o -o jitterentropy-rngd --static
```

Still binary isn't static
```
/ # ldd $(which jitterentropy-rngd)
        /lib/ld-musl-x86_64.so.1 (0x7f7b01c6d000)
```

Sorry, I'm beginner with compile binaries...

**Comment by smuellerDD** [comment]
Am Samstag, 19. Dezember 2020, 21:49:08 CET schrieb pwFoo:

Hi pwFoo,

> Tried it with `.configure` (not exists) and added to make:
> ```
> make LDFLAGS="-static"
> ```
> ```
> make LDFLAGS="--static"
> ```

It is -static.

Either you extend the Makefile LDFLAGS variable or you have to invoke make 
with the full variable extended by -static.

```
$ make
cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv --
param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-
field-initializers -Wshadow -Wswitch-enum -O2 -fstack-protector-strong    -c -
o jitterentropy-base.o jitterentropy-base.c
cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv --
param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-
field-initializers -Wshadow -Wswitch-enum -O2 -fstack-protector-strong    -c -
o jitterentropy-rngd.o jitterentropy-rngd.c
cc jitterentropy-base.o jitterentropy-rngd.o -o jitterentropy-rngd -Wl,-
z,relro,-z,now -pie -static  -lrt -lpthread
$ ldd jitterentropy-rngd
        not a dynamic executable
```
> 
> Compiled (example with --static, but both identical...)
> ```
> cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv
> --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align
> -Wmissing-field-initializers -Wshadow -Wswitch-enum -O2
> -fstack-protector-strong    -c -o jitterentropy-base.o jitterentropy-base.c
> cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv
> --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align
> -Wmissing-field-initializers -Wshadow -Wswitch-enum -O2
> -fstack-protector-strong    -c -o jitterentropy-rngd.o jitterentropy-rngd.c
> cc jitterentropy-base.o jitterentropy-rngd.o -o jitterentropy-rngd --static
> ```
> 
> Still binary isn't static
> ```
> / # ldd $(which jitterentropy-rngd)
>         /lib/ld-musl-x86_64.so.1 (0x7f7b01c6d000)
> ```
> 
> Sorry, I'm beginner with compile binaries...


Ciao
Stephan

**Comment by pwFoo** [comment]
Hi,

I don't understand how / why, but it doesn't work. Should work with added `-static` in Makefile?
```
LDFLAGS ?=-Wl,-z,relro,-z,now -pie -static
```

Full dockerfile.
```
ARG     BASE_IMG=alpine:latest

FROM    $BASE_IMG AS base

RUN     apk --update --no-cache upgrade



FROM    base as build

RUN     apk --update --no-cache add wget bc build-base gawk xorriso openssl-dev bison flex linux-headers perl rsync git argp-standalone gettext

ENV     BDIR=/out

RUN     git clone https://github.com/smuellerDD/jitterentropy-rngd.git $BDIR

WORKDIR $BDIR

#RUN    sed -i '/^LDFLAGS ?=/ s/$/ -static/' Makefile
#RUN    grep LDFLAGS Makefile
#RUN    make

#RUN    make LDFLAGS="-Wl,-z,relro,-z,now -pie -static"

RUN     LDFLAGS="-Wl,-z,relro,-z,now -pie -static" make

RUN     strip /out/jitterentropy-rngd

RUN     ldd /out/jitterentropy-rngd


FROM    alpine
 #scratch

COPY    --from=build /out/jitterentropy-rngd /usr/bin/
COPY    --from=build /lib/ld-musl-x86_64.so.1 /lib/ld-musl-x86_64.so.1

CMD     [ "jitterentropy-rngd", "-vvvvv" ]
```

Binary is still not static.
```
Step 11/18 : RUN        make
 ---> Running in e373ccbf43b0
cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-field-initializers -Wshadow -Wswitch-enum -O2 -fstack-protector-strong    -c -o jittc
cc -Wextra -Wall -pedantic -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fwrapv --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-field-initializers -Wshadow -Wswitch-enum -O2 -fstack-protector-strong    -c -o jittc
cc jitterentropy-base.o jitterentropy-rngd.o -o jitterentropy-rngd -Wl,-z,relro,-z,now -pie -static  -lrt -lpthread
Removing intermediate container e373ccbf43b0
 ---> 379cb6f99fdb
[...]
Step 14/18 : RUN        ldd /out/jitterentropy-rngd
 ---> Running in 8f150cf1357b
        /lib/ld-musl-x86_64.so.1 (0x7f3a8c179000)
Removing intermediate container 8f150cf1357b
```

**Comment by smuellerDD** [comment]
Am Sonntag, dem 20.12.2020 um 06:32 -0800 schrieb pwFoo:
> Hi,
> 
> I don't understand how / why, but it doesn't work. Should work with added `-
> static` in Makefile?

Yes, it does on my system. But this requires that the used libraries (c,
pthreads and rt) are static as well.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Works for me. Please reopen if issue persists.
