### ISSUE TITLE
Container could run with readonly rootfs

### ISSUE THREAD

**Issue by pwFoo** [smuellerDD/jitterentropy-rngd#17]
It should be possible to start the container `--read-only`? No need to write inside of the container rootfs?
```
docker run --rm -ti --cap-add=SYS_ADMIN --cap-drop=ALL --name=rngd --network=none --read-only jrngd:latest jitterentropy-rngd -vvvvvvvvvvvvvvvvvv
```

Seems to work
```
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install termination signal handler
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 2841 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 2842 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
^Cjitterentropy-rngd - Debug: Shutting down cleanly
```

**Comment by smuellerDD** [comment]
Am Samstag, dem 19.12.2020 um 07:51 -0800 schrieb pwFoo:
> It should be possible to start the container `--read-only`? No need to write
> inside of the container rootfs?

The jitteretropy-rngd does not need any R/W files. Its only purpose and action
is to open /dev/random and IOCTL data into it. The noise source works without
touching any device other than the CPU and RAM.

> ```
> docker run --rm -ti --cap-add=SYS_ADMIN --cap-drop=ALL --name=rngd --
> network=none --read-only jrngd:latest jitterentropy-rngd -vvvvvvvvvvvvvvvvvv
> ```
> 
> Seems to work
> ```
> jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32
> bytes of entropy
> jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
> jitterentropy-rngd - Debug: Install termination signal handler
> jitterentropy-rngd - Debug: Install alarm signal handler
> jitterentropy-rngd - Debug: Polling /dev/random
> jitterentropy-rngd - Verbose: Wakeup call for alarm on
> /proc/sys/kernel/random/entropy_avail
> jitterentropy-rngd - Debug: Sufficient entropy 2841 available
> jitterentropy-rngd - Debug: Install alarm signal handler
> jitterentropy-rngd - Debug: Polling /dev/random
> jitterentropy-rngd - Verbose: Wakeup call for alarm on
> /proc/sys/kernel/random/entropy_avail
> jitterentropy-rngd - Debug: Sufficient entropy 2842 available
> jitterentropy-rngd - Debug: Install alarm signal handler
> jitterentropy-rngd - Debug: Polling /dev/random
> ^Cjitterentropy-rngd - Debug: Shutting down cleanly
> ```
>

**Comment by pwFoo** [comment]
Thanks, maybe could be added to readme file that it could be run on read only filesystem?
I'll close that issue here because it just was a question / discussion.

**Comment by smuellerDD** [comment]
Am Samstag, dem 19.12.2020 um 08:57 -0800 schrieb pwFoo:
> Thanks, maybe could be added to readme file that it could be run on read
> only filesystem?
> I'll close that issue here because it just was a question / discussion.
> 

Added to the man page.

Thanks
Stephan
