### ISSUE TITLE
[Question] In case if I run it using docker-compose will it apply entropy for the host?

### ISSUE THREAD

**Issue by evgeny-s** [smuellerDD/jitterentropy-rngd#18]
Basically the question is in the title.
Another one:
I'm running it via:
```
docker-compose up -d
```
When I want to see logs, it is nothing. Is it expected? See below:
```
# docker-compose logs -f rngd
Attaching to jitterentropy-rngd_rngd_1
```

**Comment by smuellerDD** [comment]
Before I answer: I am not using Docker, so I cannot provide detailed answers to the docker-compose application. But based on the description, docker-compose seems to create a container based on namespaces. The question is, which namespaces are used.

Title question: The rngd needs CAP_SYS_ADMIN of the user-namespace from the host. That said, if you do not use a user namespace, and rngd is started as root inside a container, the kernel will receive entropy. If you use the user namespace with the rngd, it will not be able to insert entropy into the kernel.

Second question: jitterentropy-rngd does not create logs when started without options. If you want to see its operation, use one or more -v options.

**Comment by smuellerDD** [comment]
Closing the report - if it is still an issue, please reopen.
