### ISSUE TITLE
Timer too coarse on 64bit. Fine on 32bit

### ISSUE THREAD

**Issue by drunkenmaster2** [smuellerDD/jitterentropy-rngd#2]
Version jitterentropy-rngd 1.0.6
Version Jitterentropy Core 2000100
Machine: VM on VMware ESXi5.5

On 32bit it's woking fine.
uname -a
Linux gw-5fc0b7 2.6.18-92cp #1 SMP Fri Apr 7 13:46:47 IDT 2017 i686 i686 i386 GNU/Linux

On 64bit initialization fails due to "too coarse timer" (error 2)
uname -a
Linux gw-5fc0b7 2.6.18-92cpx86_64 #1 SMP Fri Apr 7 13:55:39 IDT 2017 x86_64 x86_64 x86_64 GNU/Linux
./jitterentropy-rngd
jitterentropy-rngd - Error: The initialization of CPU Jitter RNG failed with error code 2

I am using gcc version 4.1.2 20070626 (Red Hat 4.1.2-14) and had to modify the Makefile (changing "-fstack-protector-strong" to "-fstack-protector").

**Comment by smuellerDD** [comment]
Am Donnerstag, 14. Dezember 2017, 10:18:53 CET schrieb drunkenmaster2:

Hi drunkenmaster2,

> Version jitterentropy-rngd 1.0.6
> Version Jitterentropy Core 2000100
> Machine: VM on VMware ESXi5.5
> 
> On 32bit it's woking fine.
> uname -a
> Linux gw-5fc0b7 2.6.18-92cp #1 SMP Fri Apr 7 13:46:47 IDT 2017 i686 i686
> i386 GNU/Linux
> 
> On 64bit initialization fails due to "too coarse timer" (error 2)
> [~]uname -a
> Linux gw-5fc0b7 2.6.18-92cpx86_64 #1 SMP Fri Apr 7 13:55:39 IDT 2017 x86_64
> x86_64 x86_64 GNU/Linux [~]./jitterentropy-rngd
> jitterentropy-rngd - Error: The initialization of CPU Jitter RNG failed with
> error code 2

What time source is present in your system?

Please send the content of /sys/devices/system/clocksource/clocksource0/
available_clocksource and /sys/devices/system/clocksource/clocksource0/
current_clocksource
> 
> I am using gcc version 4.1.2 20070626 (Red Hat 4.1.2-14) and had to modify
> the Makefile (changing "-fstack-protector-strong" to "-fstack-protector").

Strange -- which error did you get when compiling?



Ciao
Stephan

**Comment by drunkenmaster2** [comment]
Hi Stephan,

on a 64bit kernel:
cat /sys/devices/system/clocksource/clocksource0/available_clocksource
jiffies
cat /sys/devices/system/clocksource/clocksource0/current_clocksource
jiffies

on a 32bit kernel:
cat /sys/devices/system/clocksource/clocksource0/available_clocksource
acpi_pm jiffies hpet tsc pit
cat /sys/devices/system/clocksource/clocksource0/current_clocksource
tsc

Regarding the gcc error, it's simply an unsupported option:
make
gcc -Wextra -Wall -pedantic -fPIE -pie -fstack-protector-strong -fwrapv --param ssp-buffer-size=4 -O0     -c -o jitterentropy-base.o jitterentropy-base.c
cc1: error: unrecognized command line option "-fstack-protector-strong"
make: *** [jitterentropy-base.o] Error 1

Thank you
Amit

**Comment by drunkenmaster2** [comment]
Hi Stephan,
Could you please advise?

**Comment by smuellerDD** [comment]
Am Sonntag, 17. Dezember 2017, 09:02:22 CET schrieb drunkenmaster2:

Hi drunkenmaster2,

(sorry for the delay)

> Hi Stephan,
> 
> on a 64bit kernel:
> admin@gw-5fc0b7[~]cat
> /sys/devices/system/clocksource/clocksource0/available_clocksource jiffies
> admin@gw-5fc0b7[~]cat
> /sys/devices/system/clocksource/clocksource0/current_clocksource jiffies

This is the issue: jiffies is a "timer" that increments by one every 
millisecond. This timer cannot be used at all.
> 
> on a 32bit kernel:
> admin@gw-5fc0b7[~]cat
> /sys/devices/system/clocksource/clocksource0/available_clocksource acpi_pm
> jiffies hpet tsc pit
> admin@gw-5fc0b7[~]cat
> /sys/devices/system/clocksource/clocksource0/current_clocksource tsc

This clock source should always work.

I have no idea why you only see jiffies as clocksource in your 64 bit kernel.

In this case you must use the direct way: depending on the hardware type, you 
may want to use one of the header files in [1] as a drop-in replacement for 
the jitterentropy-base-user.h. Especially the jent_get_nstime function is the 
key here.

[1] https://github.com/smuellerDD/jitterentropy-library/tree/master/arch
> 
> Regarding the gcc error, it's simply an unsupported option:
> make
> gcc -Wextra -Wall -pedantic -fPIE -pie -fstack-protector-strong -fwrapv
> --param ssp-buffer-size=4 -O0     -c -o jitterentropy-base.o
> jitterentropy-base.c cc1: error: unrecognized command line option
> "-fstack-protector-strong" make: *** [jitterentropy-base.o] Error 1

Thanks for letting me know. Though, as I do not use the autotools I am unsure 
how to catch that issue in a generic form. Any ideas?
> 
> Thank you
> Amit



Ciao
Stephan

**Comment by drunkenmaster2** [comment]
Hi Stephan,
I will integrate the direct method for my arch (x86) as you suggested.
Thank you for your support.
