### ISSUE TITLE
sysconf constants causing build issues on systems that use 'musl' libc instead of glibc

### ISSUE THREAD

**Issue by stoickish** [smuellerDD/jitterentropy-rngd#22]
I attempted to build the latest build (1.2.4) on a Linux distro called OpenWRT, which uses 'musl' libc by default.  The build now breaks due to the three referenced constants [here](https://github.com/smuellerDD/jitterentropy-rngd/blob/master/jitterentropy-base-user.h#L234-L236).

A few notes for context here are:

- 1.2.3 built successfully
- Switching from 'musl' to 'glibc' allows the build to complete successfully

One suggestion to avoid this issue might be to add a preprocessor directive prior to the execution of those 'sysconf' calls like:

`#if defined(_SC_LEVEL1_DCACHE_SIZE) && defined(_SC_LEVEL2_CACHE_SIZE) && defined(_SC_LEVEL3_CACHE_SIZE)`

**Comment by smuellerDD** [comment]
Am Dienstag, 31. August 2021, 03:30:56 CEST schrieb stoickish:

Hi stoickish,

> I attempted to build the latest build (1.2.4) on a Linux distro called
> OpenWRT, which uses 'musl' libc by default.  The build now breaks due to
> the three referenced constants
> [here](https://github.com/smuellerDD/jitterentropy-rngd/blob/master/jittere
> ntropy-base-user.h#L234-L236).
> 
> A few notes for context here are:
> 
> - 1.2.3 built successfully
> - Switching from 'musl' to 'glibc' allows the build to complete successfully
> 
> One suggestion to avoid this issue might be to add a preprocessor directive
> prior to the execution of those 'sysconf' calls like:
> 
> `#if defined(_SC_LEVEL1_DCACHE_SIZE) && defined(_SC_LEVEL2_CACHE_SIZE) &&
> defined(_SC_LEVEL3_CACHE_SIZE)`

Thanks for the report. Can you please give the update to the rngd code base a 
try?

Thanks


Ciao
Stephan

**Comment by stoickish** [comment]
Yup, looks like the changes you made fixed the build on the 'musl' OpenWRT platform I was using.  Thanks!
