### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by xnoreq** [smuellerDD/jitterentropy-rngd#23]
I've compiled the latest master with gcc 11.1.0 and the following flags:
```
CFLAGS :=-march=x86-64 -mtune=generic -Wextra -Wall -pedantic -fwrapv --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-field-initializers -Wshadow -Wswitch-enum -O0
LDFLAGS :=-Wl,-z,relro,-z,now -pie
```

The process (jitterentropy-rngd) uses 66904 kB RSS memory according to ps. This is inside an 8-core AMD Zen 2 virtual machine.

**Comment by xnoreq** [comment]
In a 4-core VM on the same host I've seen memory usage up to about 120 MB.

**Comment by smuellerDD** [comment]
Am Sonntag, 12. September 2021, 18:38:59 CEST schrieb xnoreq:

Hi xnoreq,

> In a 4-core VM on the same host I've seen memory usage up to about 120 MB.

Yes, I am already bringing it down again. The first patch has been deployed to 
the jitterentropy-library which will be ported to the rngd. A second patch is 
currently tested and should land later tonight.


Ciao
Stephan

**Comment by xnoreq** [comment]
That's good to hear. I've switched all my servers and VMs back to haveged for the time being. It uses consistently less than 5MB  RSS across a range of hardware and VM configurations.

**Comment by smuellerDD** [comment]
Am Montag, 13. September 2021, 21:22:52 CEST schrieb xnoreq:

Hi xnoreq,

> That's good to hear. I've switched all my servers and VMs back to haveged
> for the time being. It uses consistently less than 5MB  RSS across a range
> of hardware and VM configurations.

I pushed a new version of the rngd.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Patch is assumed to be working, closing.
