### ISSUE TITLE
Should Xen, VirtualBox implement something similar to QEMU / KVM's `virtio-rng`? Keep feeding the host's /dev/random into the VM?

### ISSUE THREAD

**Issue by adrelanos** [smuellerDD/jitterentropy-rngd#28]
[virtio-rng](https://wiki.qemu.org/Features/VirtIORNG) seems conceptually nice. Unfortunately as far as I know, it is only available for QEMU / KVM.

Should Xen, VirtualBox implement something similar to virtio-rng?

To shut down any concerns about entropy quality in VMs, I think because in its basic operation virtio-rng keeps feeding the host's /dev/random to a device in the VM that appears as /dev/random. [1]

To my knowledge, Xen, VirtualBox do not have such a feature.

What's the impact of this? Is this a minor missing enhancement or critical issue that could lead to insecure keys created in such VMs?

----

[1] It has a lot more complex options but let's consider the easy, default case.

**Comment by dermotbradley** [comment]
There is also VMGENID (which for Linux VM requires kernel with CONFIG_VMGENID="y" or "m" and module loaded) which is supported by at least Hyper-V, [QEMU](https://www.qemu.org/docs/master/specs/vmgenid.html), and [VMWare](https://kb.vmware.com/s/article/2041872) hypervisors.

"A virtual machine generation identifier consists of a unique buffer of 128-bit interpreted as cryptographic random integer identifier."

**Comment by dermotbradley** [comment]
@adrelanos "virtio-rng keeps feeding the host's /dev/random to a device in the VM that appears as /dev/random" - nope, the VM has a /dev/hwrng device (like on a real machine with a hardware RNG).

From the QEMU [docs]( https://wiki.qemu.org/Features/VirtIORNG): "VirtIO RNG is a paravirtualized device that is exposed as a hardware RNG device to the guest".

**Comment by smuellerDD** [comment]
> 
> Should Xen, VirtualBox implement something similar to virtio-rng?
> 

That is a good question. Let us understand why such mechanism exists in the first place. You could construct a VM with one or more of the following being applicable:

1. without any real device - by extension its noise source based on interrupts fails (e.g. /dev/random)
2. with a coarse timer (e.g. RDTSC can be trapped by the hypervisor and HPET's may not be accessible to guests) - by extension all noise sources resting on a high-resolution timer fail (e.g. /dev/random, Jitter RNG using external timer, havegd)
3. with only one CPU - by extension all noise sources generating their own high-res time stamp internally by a tight loop that is sampled by a separate thread fail (e.g. Jitter RNG using internal timer)
4. without access to hardware RNGs (e.g. RDSEED can be trapped by the hypervisor) - by extension they cannot be used as seeding purpose

So, you see there are many possibilities where entropy sources in guests fail based on how the hypervisor is configured or operates. Surely there are more possibilities, but those listed above should cover common cases.

If *any* of the possibilities apply to Xen or VirtualBox (note, I have done a code audit of VirtualBox and found it *does* trap RDTSC, but I do not know what it does with it), then something like Virtio-RNG is important.

**Comment by smuellerDD** [comment]
> There is also VMGENID (which for Linux VM requires kernel with CONFIG_VMGENID="y" or "m" and module loaded) which is supported by at least Hyper-V, [QEMU](https://www.qemu.org/docs/master/specs/vmgenid.html), and [VMWare](https://kb.vmware.com/s/article/2041872) hypervisors.

This ID is only used to force a reseed of the in-kernel CSPRNG after a VM-"fork" is detected. It is akin to the fork-detection logic in user space to force a reseed after a fork to ensure that the two instances do not have the same DRNG state.

**Comment by smuellerDD** [comment]
> @adrelanos "virtio-rng keeps feeding the host's /dev/random to a device in the VM that appears as /dev/random" - nope, the VM has a /dev/hwrng device (like on a real machine with a hardware RNG).
> 
> From the QEMU [docs](https://wiki.qemu.org/Features/VirtIORNG): "VirtIO RNG is a paravirtualized device that is exposed as a hardware RNG device to the guest".

Virtio-RNG works as follows: QEMU opens /dev/random on the host side and register an "RNG" device in the guest's device table. The guest now can implement a device driver (e.g. the Linux kernel has a virtio-rng client driver) which reads the device. When reading it, QEMU receives the read request and pulls data from the opened /dev/random. The Linux kernel virtio-rng driver (drivers/char/hw_random/virtio-rng.c) is simply registering itself as part of the HW-RAND framework delivering its data to /dev/hwrng. In addition, the HW-RAND framework creates an in-kernel thread (the thread-function is drivers/char/hw_random/core.c:hwrng_fillfn) which samples the registered HW-RAND drivers and inserts its data into random.c via the add_hwgenerator_randomness API. I.e. this is the in-kernel version of an "rngd".
